### ISSUE TITLE
Emojis render in preview, not in actual document

### ISSUE THREAD

**Issue by KronosTheLate** [Enter-tainer/typst-preview#138]
Based on "Therefore, if you encounter any rendering issue, please report it to this repo other than official typst repo.", I wanted to report that when I added three emojis from the [emoji module](https://typst.app/docs/reference/symbols/emoji), the preview had them just fine, while the actual PDF did not. This is related to https://github.com/typst/typst/issues/144.

**Comment by Enter-tainer** [comment]
🤣 yes, official typst has problem supporting emoji font when comping to pdf. (note that when compiling to png and svg, emoji font works). typst-preview use a somehow customized svg export to display the preview so emoji font is supported. 

I would close this as not planned because typst-preview's behavior is more "correct". I think the upstream issue can be resolved in a not too far future :+1:

**Comment by Enter-tainer** [comment]
Note that similar thing also happens in official webapp: it appears in preview but no in pdf. So be careful with that

**Comment by LarsKue** [comment]
Why was this closed? Seems very much like a bug in an otherwise desirable feature.

**Comment by Enter-tainer** [comment]
it's an upstream bug. they cannot render emojis in pdf. i think previous conversation explains why this is closed.

**Comment by LarsKue** [comment]
My bad, I confused this repo for the main typst repo 🫣
