### ISSUE TITLE
Preserve preview after reloading

### ISSUE THREAD

**Issue by George-Miao** [Enter-tainer/typst-preview#153]
When preview in VSCode tabs, after reloading (reload vscode window) the preview tab will gone and left with a blank space. I'm not sure if this is by design or not but it would be great to show preview again even after the editor is reloaded.

**Comment by Enter-tainer** [comment]
~~i haven't test this and i don't know how will "reload window" affects extensions though. but i think this should be a bug. The preview should recover itself.~~

At the time of typing, i realize why this happens. when reloading the window, the ws connection between vscode and the typst-preview server is interrupted. And the typst-preview server currently shutdown itself when this connection is closed. This makes sense because it typically only happens when vscode is exiting. I will take a closer look later and see if we can do better.

**Comment by Enter-tainer** [comment]
When vscode window is reloaded, the extension is killed. Therefore the frontend can no longer get any update. It might be better to make extension restore state through some way but I don't know how.

![Image](https://github.com/Enter-tainer/typst-preview/assets/25521218/392d4ad1-d2b1-436c-9a61-75789a01348c)

**Comment by George-Miao** [comment]
Do you know how does vscode pdf viewer restore its state after reload? Apparently pdf viewers are preserved.

**Comment by Enter-tainer** [comment]
pdf viewer works in pure frontend and doesnt rely on any external services.

**Comment by Enter-tainer** [comment]
i cannot find doc describing what "reload window" does exactly. from my knowledge i guess it would kill extension server and restart it. so basically the extension need to bring up it self when vscode is opened. 

another problem is that currently we use randomized ports to avoid collision and ensure you can start multiple preview instances. but when the server is killed and vscode restarted, the port number is permanently lost. so even we can bring up the server, we cannot choose the correct port number.

from my experience reloading window doesnt happens very frequently. and i think this won't affect most users. we have a project table and you may see stuffs with higher priority.

**Comment by Enter-tainer** [comment]
In latest vscode, webview tab disappears after reloading. I'm closing this since it becomes impossible
