### ISSUE TITLE
Double clicking a heading makes the preview go to the table of contents

### ISSUE THREAD

**Issue by ziiirozone** [Enter-tainer/typst-preview#241]
Hello !
If you have a document with a table of contents created with the outline function and you double click the heading in the document, it will make the preview jump to where the heading is in the table of contents instead of showing you where it actually is.

If you create a typst doc with 

#outline() 
#pagebreak() 
= Title 
#pagebreak();
hello 

and you go to the page with "hello" written in the preview then you double click the heading in the .typ doc it will do it. 

I believe it should show you the actual heading instead of the table of contents.

I use vs code version 1.86.0 (up to date) with the version 0.10.7 of the typst preview extension.

The extension is great btw, loving it !

**Comment by Myriad-Dreamin** [comment]
The jump destination is provided by typst compiler and perhaps typst-preview cannot make a more smarter jump over it. You can check webapp, when you click a heading in the document, webapp also takes you to the table of contents.

The root cause is that both the text in the table of contents and the text in the heading are from the same source location: your clicking the heading in the document. When there are multiple jump destinations, the compiler will take you to the first occurrence of the text -- so the text in the table of contents.

We can transfer this issue to typst/typst, like the [similar issue, Jump to code does not work within a code block](https://github.com/Enter-tainer/typst-preview/issues/182).

**Comment by ziiirozone** [comment]
Thanks for your answer ! I didn't know it was handled by typst and I will be transfering to the right github, have a great day !
